# Generated by Django 5.2 on 2026-02-14 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_team_and_membership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspaces_created", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "team",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspaces", to="core.team"),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="boards_created", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "workspace",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="boards", to="core.workspace"),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="columns", to="core.board"),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True, default="")),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[("normal", "Normal"), ("super", "Super")],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("labels", models.JSONField(blank=True, default=list)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="core.board"),
                ),
                (
                    "column",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="core.column"),
                ),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tasks_created", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "assignees",
                    models.ManyToManyField(blank=True, related_name="tasks_assigned", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["position", "-updated_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="task_comments", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "task",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="core.task"),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.UniqueConstraint(fields=("team", "name"), name="unique_workspace_name_per_team"),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(fields=["team", "-updated_at"], name="core_worksp_team_id_5e5f61_idx"),
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.UniqueConstraint(fields=("workspace", "name"), name="unique_board_name_per_workspace"),
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(fields=["workspace", "-updated_at"], name="core_board_workspa_0d238a_idx"),
        ),
        migrations.AddConstraint(
            model_name="column",
            constraint=models.UniqueConstraint(fields=("board", "name"), name="unique_column_name_per_board"),
        ),
        migrations.AddIndex(
            model_name="column",
            index=models.Index(fields=["board", "position"], name="core_column_board_id_7f8f1a_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["board", "column", "position"], name="core_task_board_i_8de4cd_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["board", "-updated_at"], name="core_task_board_i_7d2bb0_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["due_date"], name="core_task_due_da_6f97ae_idx"),
        ),
        migrations.AddIndex(
            model_name="taskcomment",
            index=models.Index(fields=["task", "created_at"], name="core_taskco_task_id_dad1a7_idx"),
        ),
    ]
